maybe that's the start done

diff --git a/start/action.yaml b/start/action.yaml
--- a/start/action.yaml
+++ b/start/action.yaml
@@ -72,6 +72,25 @@ runs:
         export TF_VAR_runner_token=$runner_token
         terraform init
         terraform apply --auto-approve
+        instance_id=$(terraform output -raw id)
+        echo "Waiting for repository runner to be registered ..."
+        for i in {1..12}; do
+            sleep 10
+            runner_id=$(gh api -X GET "repos/$GH_REPO/actions/runners" -f per_page=100 \
+              | jq -r --arg INSTANCE_ID "$instance_id" '.runners[] | select(.name == $INSTANCE_ID and .status == "online") | .id')
+            if [ -n "$runner_id" ]; then
+                break
+            fi
+        done
+        if [ -z "$runner_id" ]; then
+            echo "Runner registration failed (timed out). Terminating instance ..."
+            aws ec2 terminate-instances --instance-ids "$instance_id"
+            exit 1
+        else
+            echo "::set-output name=runner-id::$runner_id"
+            echo "Repository runner started (ID: $runner_id)"
+        fi
+        
         
       env:
         TYPE:         ${{ inputs.type }}
